development:
  adapter: postgresql
  encoding: unicode
  database: tasks_development
  pool: 5
  username: tasksbackend
  password: tasksbackend

test:
  adapter: postgresql
  encoding: unicode
  database: tasks_test
  pool: 5
  username: tasksbackend
  password: tasksbackend
